*  This program simulates, for arbitrarily given N (# of assets) and T (sample * size, a set of true mean and covariance parameters; then a set of N asset retturns drawn from a normal distribution with those parameters, and then see how well for estimated optimal portfolio performs.
***
***
The purpose is to understand how estimation errors affcet the performance.
 

In [22]:
import numpy as np
import scipy.linalg as la      # we need the package to compute the Cholesky decomposition

np.random.seed(1234)         # so that the random numbers will be the same each time running the program

# We set the parameters first. 
# Although one can enter parameters manually, below is a simple sysmatic way
# to generate them

N = 3    # an arbitrary number of assets 
T = 120    # sample size, such as 10 years of month data

mu = np.random.randn(N,1)
mu = np.exp(mu)  # get a vector of positive expected return parameters

L1 = np.random.randn(N,N)  # get a random matrix 
L = np.tril(L1)        # get only its lower traingular part
np.fill_diagonal(L, 1)  # replace the diagonal element by 1
                        # So L can be a Cholesky decomposition
                      # Note: the output is L with values replaced  
 
V = np.matmul(L.T,L)    # V = L'*L,  our covariance matrix
                         # it will be positive definite by design

# Assume the riskfree rate is zero
# get the theoretical Sharpe ratio from formula (2.60) of the Lecture Notes
#          

VI = np.linalg.inv(V)    # The inverse of S
                         # np.linalg.inv is a np function 
print(mu.shape)
print(VI)
print(mu)
B = np.matmul(VI, mu)       #  the vector VI*mu

SR = np.matmul(mu.T,B)       #   mu'*VI*mu
     
# SR = np.sqrt(SR)

print(' The # of assets and sample size  \n')
print('          {}  {} \n'.format(N, T))   
print('  The theoretical Sharpe ratio given the parameters  \n')
print(SR)

(3, 1)
[[ 1.         -0.85958841  3.23124234]
 [-0.85958841  1.73889224 -3.9275742 ]
 [ 3.23124234 -3.9275742  12.76350922]]
[[1.6022921 ]
 [0.30392458]
 [4.19002612]]
 The # of assets and sample size  

          3  120 

  The theoretical Sharpe ratio given the parameters  

[[259.35468089]]


In [5]:
L1 = la.cholesky(V0)             # Cholesky decomposition:  V0 = L1'*L1

L = L1.T                         # V0 = L*L',  L=L1'
e = np.random.randn(3,1)   
Y = np.matmul(L,e)              # Y = L*e,  a draw from normal with covariance matrix V0

V = np.matmul(L1.T,L1)              #   verify V0 = L1'*L1



L = np.array(L)      # convert list to array to apply np.functions
L.shape = (N,N)      # make sure it is NxN matrix
LT = np.transpose(L)
print(L.shape)

VI = np.linalg.inv(V)    # The inverse of S
                         # np.linalg.inv is a np function 
SR1 = np.dot(np.dot(mu, VI), mu)
SR = np.sqrt(SR1)

print(' The # of assets and sample size  \n')
print('          {}  {} \n'.format(N, T))   
print('  The theoretical Sharpe ratio given the parameters  \n')
print(SR)






##  A verification: draw 100,000 of them and see whether they have the desired moments
        
        
Z = np.ones((1000000,3))    # define Z to store the draws   
 
for i in range (1000000):
    e = np.random.randn(3,1)    
    Y = np.matmul(L,e)
    Z[i,:] = Y.T
  

CovY = np.cov(Z.T)                        # the covariance matrix estimate, 2 by 2

print(' The covariance matrix estimate of the data  \n')
print(CovY)
print (V0) 

 The covariance matrix estimate of the data  

[[1.00199578 0.09938527 0.30058091]
 [0.09938527 2.00514912 0.49991961]
 [0.30058091 0.49991961 3.00407019]]
[[1.  0.1 0.3]
 [0.1 2.  0.5]
 [0.3 0.5 3. ]]
